<meta http-equiv='Content-Type' content='text/html; charset=utf-8' />
<meta http-equiv='X-UA-Compatible' content='IE=edge'>
<meta name='viewport' content='width=device-width, initial-scale=1'>

<script language='javascript' type='text/javascript' src='js/jquery-2.1.0.min.js'></script>
<script language='javascript' type='text/javascript' src='js/bootstrap.js'></script>

<link rel='stylesheet' type='text/css' href='css/bootstrap.css' />
<link rel='stylesheet' type='text/css' href='css/bootstrap-theme.css' />
<link rel='stylesheet' type='text/css' href='css/principal.css'>




